export default {
  'lint-staged': {
    '*.{ts,tsx}': 'tsc-files --noEmit types.d.ts',
    '*.{ts,tsx,js,html,json,md}': 'prettier --write',
    '*.{ts,tsx,js}': 'eslint --cache --fix',
  },
  tsconfig: {
    baseUrl: '.',
    rootDir: '.',
    sourceMap: true,
    noEmit: true,
    emitDecoratorMetadata: true,
    experimentalDecorators: true,
    composite: false,
    declarationMap: false,
    emitDeclarationOnly: false,
    declaration: false,
    moduleResolution: 'bundler',
    jsx: 'react-native',
    allowJs: true,
    strict: true,
    allowSyntheticDefaultImports: true,
    noImplicitAny: true,
    strictPropertyInitialization: false,
    strictNullChecks: true,
    lib: ['es2022', 'dom'],
  },
  tsConfigExclude: ['**/*.cjs', '**/*.mjs', 'node_modules', 'dist'],
  gitIgnore: ['.eslintcache', '*.tsbuildinfo'],
};
