export const dependencies = {
  'expo-app': {
    '@ronas-it/react-native-common-modules': '~2.0.1',
    'react-native-mmkv': '^4.3.1',
    'expo-constants': '~56.0.18',
    'expo-dev-client': '~56.0.21',
    'expo-router': '~56.2.12',
    'react-native-safe-area-context': '~5.7.0',
    'react-native-screens': '4.25.2',
    expo: '~56.0.13',
    'expo-linking': '~56.0.14',
    'expo-splash-screen': '~56.0.11',
    'expo-status-bar': '~56.0.4',
    'expo-updates': '~56.0.20',
    'expo-insights': '~56.0.19',
    'expo-localization': '~56.0.6',
    'i18n-js': '~4.5.1',
    'lodash-es': '^4.17.21',
    react: '19.2.3',
    'react-dom': '19.2.3',
    'react-native': '0.85.3',
    'react-native-svg': '15.15.4',
    'react-native-svg-transformer': '~1.5.1',
  },
  'next-app': {
    'next-intl': '^4.5.3',
    'lodash-es': '^4.17.21',
    'class-transformer': '^0.5.1',
    next: '~16.1.5',
    react: '~19.2.4',
    'react-dom': '~19.2.4',
  },
  'api-client': {
    '@ronas-it/axios-api-client': '^0.3.0',
  },
  auth: {
    luxon: '^3.7.2',
  },
  'next-auth': {
    'js-cookie': '^3.0.5',
  },
  'rn-styles': {
    'react-native-unistyles': '^3.2.4',
    'react-native-edge-to-edge': '^1.8.1',
    'react-native-nitro-modules': '0.35.6',
  },
  'ui-kit': {
    'expo-constants': '~56.0.18',
    'react-native-reanimated': '4.3.1',
    'react-native-worklets': '0.8.3',
    'expo-image': '~56.0.11',
    'expo-router': '~56.2.12',
    'react-native-toast-message': '^2.3.3',
    'react-native-keyboard-controller': '1.21.6',
  },
  store: {
    '@ronas-it/rtkq-entity-api': '^1.1.1',
    'react-redux': '^9.2.0',
  },
  form: {
    '@hookform/resolvers': '^5.2.2',
    'react-hook-form': '^7.65.0',
    yup: '^1.7.1',
  },
  sentry: {
    expo: {
      '@sentry/react-native': '~7.11.0',
    },
    next: {
      '@sentry/nextjs': '^10.27.0',
    },
  },
};

export const devDependencies = {
  'code-checks': {
    '@eslint/compat': '^1.4.0',
    '@eslint/eslintrc': '^3.3.1',
    '@eslint/js': '^9.37.0',
    eslint: '^9.37.0',
    prettier: '^3.6.2',
    'eslint-config-prettier': '^10.1.8',
    'eslint-import-resolver-typescript': '^4.4.4',
    'eslint-plugin-import': '^2.32.0',
    'eslint-plugin-jsx-a11y': '^6.10.2',
    'eslint-plugin-react': '^7.37.5',
    'eslint-plugin-react-hooks': '^7.0.0',
    'eslint-plugin-unused-imports': '^4.2.0',
    husky: '^9.1.7',
    '@stylistic/eslint-plugin': '^4.4.1',
    '@typescript-eslint/eslint-plugin': '^8.46.0',
    '@typescript-eslint/parser': '^8.46.0',
    'tsc-files': '^1.1.4',
    'typescript-eslint': '^8.46.0',
    stylelint: '^17.12.0',
    'stylelint-config-standard-scss': '^17.0.0',
  },
  'expo-app': {
    '@types/lodash-es': '^4.17.12',
    '@types/react': '~19.2.0',
    '@types/react-dom': '~19.2.0',
    '@expo/cli': '^56.1.16',
    'reactotron-react-native': '^5.1.18',
    'reactotron-redux': '^3.2.1',
    metro: '^0.83.7',
    'metro-config': '~0.83.7',
  },
  'next-app': {
    'eslint-config-next': '^16.0.3',
    '@types/lodash-es': '^4.17.12',
    '@types/react': '~19.1.10',
    '@types/react-dom': '~19.1.11',
    'babel-plugin-react-compiler': '^1.0.0',
  },
  'repo-config': {
    syncpack: '^15.3.2',
    'cross-env': '^10.1.0',
  },
  auth: {
    '@types/luxon': '3.7.2',
  },
  'next-auth': {
    '@types/js-cookie': '^3.0.6',
  },
};
