---
name: import-figma-assets
description: >
  Export the favicon and icon sprite from a Figma UI-kit page's "Web assets" block into this app's
  Next.js app directory and UI-kit library, and wire the sprite path into the UI-kit's `Icon`
  component. Requires a link to a Figma page and, ideally, a connected Figma MCP server. Use
  whenever asked to "import figma assets/icons", "export the favicon from figma", "import the icon
  sprite", or similar. This app was scaffolded with `@ronas-it/nx-generators` (`next-app
  --withMantine`); can run standalone or as a follow-up step after the `import-figma-ui` skill,
  which hands off here for its "Web assets" phase.
---

# Import Figma assets

This file lives under `.agents/skills/import-figma-assets/`, following the [Agent Skills
convention][agent-skills] — many coding agents (Claude Code, Codex CLI, and others) auto-discover
and load skills from `.agents/skills/**/SKILL.md` without any tool-specific adapter file. A
Claude-Code-specific pointer to this file lives at `.claude/skills/import-figma-assets/SKILL.md`.

[agent-skills]: https://agentskills.io/specification

## Scope — what this skill assumes about the app

This app was generated by `@ronas-it/nx-generators`' `next-app` generator with `--withMantine`
(or the underlying `mantine` generator run some other way). That means:

- `apps/<app>/app/` is the Next.js App Router root (this app's actual page tree may live one level
  deeper, e.g. `apps/<app>/app/[locale]/`, for i18n routing — the favicon convention below applies
  to the top-level `app/` directory regardless).
- `libs/<app>/shared/ui/ui-kit/src` exists, with an `Icon` component at
  `src/lib/icon/component.tsx` + `component.module.scss`.

If more than one app under `apps/` matches this shape, ask the user which one this import targets
before doing anything — don't guess.

## Progress reporting (required)

If you're running standalone (not handed off to from `import-figma-ui`), post a short plan up
front — **Setup → Favicon → Icon sprite → Icon component wiring** — and keep it current the same
way described in `import-figma-ui`'s "Progress reporting" section: a todo/task list tool if you
have one, plain-text phase restatements if you don't, and one short sentence before each
non-trivial action.

## Phase 0 — inputs and Figma access

Skip this whole phase if you were handed a Figma link/access and a "Web assets" node ID already
(i.e. you're running as part of `import-figma-ui`) — go straight to Phase 1.

1. **Figma link.** If the user didn't already give you a link to the Figma UI-kit design page,
   ask for one.
2. **Target app.** Resolve `<app>` per the Scope section above.
3. **Figma tooling.** You need a way to read structured data and export SVGs from the Figma file
   behind that link — plain URL fetching does not work, Figma requires an authenticated session.
   Look for an already-connected Figma MCP server (e.g. the official Figma Dev Mode MCP server's
   `get_metadata`/`download_assets`/`get_screenshot`, or the community Framelink server's
   `get_figma_data`/`download_figma_images` — tool names vary by server, so search your available
   tools rather than assuming one exact name). If none is connected, tell the user plainly and ask
   whether they'd rather connect one or export the SVGs manually and hand you the files/paths.
4. Locate the top-level section named **"Web assets"** on the page behind the link.

## Phase 1 — Favicon

1. Look inside the "Web assets" block for the favicon. **There may be more than one favicon
   variant** (e.g. different marks or color treatments shown side by side for comparison) — if so,
   don't guess which one is "the" favicon; screenshot the containing frame and ask the user which
   variant to use before exporting anything.
2. Export the chosen node as SVG (ask your Figma tool for an SVG export/render of that specific
   node — if the connected tool only supports raster/PNG export, tell the user and ask them to
   export it manually from Figma instead of silently substituting a PNG).
3. Save it as `apps/<app>/app/icon.svg` — Next.js's file-based [metadata
   conventions](https://nextjs.org/docs/app/api-reference/file-conventions/icon) pick up an
   `icon.svg` directly under the app directory automatically; no code changes needed beyond adding
   the file. If a favicon file already exists there under a different name/extension (e.g.
   `favicon.ico`), ask the user before removing it — they may want to keep both.

## Phase 2 — Icon sprite

1. In the "Web assets" block, find the icons sprite asset (likely a single frame/component
   containing all the individual icons).
2. Export it as one SVG the same way, and save it to
   `libs/<app>/shared/ui/ui-kit/src/lib/assets/icons.svg` (create the `assets` directory if it
   doesn't exist).

## Phase 3 — Wire up the `Icon` component

Open `libs/<app>/shared/ui/ui-kit/src/lib/icon/`. If it doesn't exist, skip this phase and note in
the finishing summary that there was no `Icon` component to wire up.

If it exists, check `component.module.scss` for a TODO about the sprite path — the generator ships
it commented out, e.g.:

```scss
.icon {
  // TODO: uncomment when icons are added
  // background: url(../assets/icons.svg) no-repeat var(--bg-position);
  // mask: url(../assets/icons.svg) no-repeat center; mask-position: var(--bg-position);
```

Uncomment those lines now that the asset exists at `../assets/icons.svg` relative to this file
(i.e. `src/lib/assets/icons.svg`) — verify the relative path still resolves correctly rather than
assuming it's unchanged, especially if the icon component has moved.

Mapping every individual icon name to its `background-position` in the sprite (and updating the
`IconName` union in `component.tsx`) is a reasonable stretch goal if the sprite's structure makes
individual icon positions easy to determine — e.g. some Figma files ship a text layer next to the
sprite frame with ready-made SCSS (a `.icon { &_<name> { --bg-position: ...; } }` block per icon);
if you find one, use it directly instead of computing positions by hand. This isn't required by
this phase — if you skip it, say so explicitly in the finishing summary so the user knows it's
still a manual step.

## Finishing up

Post a short summary: whether the favicon and icon sprite were added (and which favicon variant
was chosen, if there was more than one), whether the `Icon` component's sprite path was uncommented,
and whether the icon-name-to-position mapping stretch goal ran or was left as a manual step. Then
ask the user to visually verify the favicon and a sample of icons in the running app.
