---
name: import-figma-vars
description: >
  Import design tokens from a Figma UI-kit page's "Variables" block into this app's shared styles
  library (`_variables.scss`) — colors, font sizes, and other responsive values. Requires a link to
  a Figma page and, ideally, a connected Figma MCP server. Use whenever asked to "import Figma
  variables", "sync design tokens from Figma", "import figma colors/tokens", or similar. This app
  was scaffolded with `@ronas-it/nx-generators` (`next-app`);
  can run standalone or as the first phase of the `import-figma-ui` skill, which hands off here and reuses the Figma
  access and node IDs this skill locates for its own remaining phases (assets, theme, fonts).
---

# Import Figma variables

This file lives under `.agents/skills/nextjs/import-figma-vars/`, following the [Agent Skills
convention][agent-skills] — many coding agents (Claude Code, Codex CLI, and others) auto-discover
and load skills from `.agents/skills/**/SKILL.md` without any tool-specific adapter file. A
Claude-Code-specific pointer to this file lives at `.claude/skills/nextjs/import-figma-vars/SKILL.md`.

[agent-skills]: https://agentskills.io/specification

## Scope — what this skill assumes about the app

This app was generated by `@ronas-it/nx-generators`' `next-app` generator. That means, for the app you're
targeting, `libs/<app>/shared/ui/styles/_variables.scss` exists and holds CSS custom properties
under `:root`, plus a `@media (max-width: $mobile)` override block for the mobile-only values. Read
it before changing anything — the exact set of tokens already there is your ground truth for
naming conventions in this specific repo, not this document.

If more than one app under `apps/` has a matching `_variables.scss`, ask the user which one this
import targets before doing anything — don't guess. If none does, stop and tell the user this
skill only applies to apps generated with this styles-library setup.

## Progress reporting (required)

If you're running standalone (not handed off to from `import-figma-ui`), post a short plan up
front — **Setup → Variables** — and keep it current the same way described in `import-figma-ui`'s
"Progress reporting" section: a todo/task list tool if you have one, plain-text phase restatements
if you don't, and one short sentence before each non-trivial action.

## Phase 0 — inputs and Figma access

Skip this whole phase if you were handed a Figma link/access and a target `<app>` already (i.e.
you're running as part of `import-figma-ui`) — go straight to Phase 1.

1. **Figma link.** If the user didn't already give you a link to the Figma UI-kit design page,
   ask for one — you cannot proceed without it. A link to a specific frame/node (not just the file
   root) is more useful if the user has it, since it saves you from searching the whole file for
   the "Variables" block.
2. **Target app.** Resolve `<app>` per the Scope section above.
3. **Figma tooling.** You need a way to read structured data (and ideally export SVGs) from the
   Figma file behind that link — plain URL fetching does not work, Figma requires an authenticated
   session. Look for an already-connected Figma MCP server:
   - In Claude Code, search your available tools for anything Figma-related (tool names vary by
     server — e.g. the official Figma Dev Mode MCP server exposes `get_metadata`, `get_code`,
     `get_variable_defs`, `get_image`/`get_screenshot`; the community Framelink server exposes
     `get_figma_data` and `download_figma_images`). Use whichever discovery mechanism your tooling
     provides (e.g. a tool-search facility) rather than assuming one exact name.
   - In another agent, check its own tool/MCP listing the same way.
   - **Prefer a variables/tokens-shaped tool** (e.g. `get_variable_defs`) over screen-scraping a
     rendered table when both are available — it gives you exact values (hex codes, numbers)
     without any risk of misreading a screenshot. That said, a tokens tool scoped to a broad frame
     may resolve only one Figma variable _mode_ (e.g. the desktop column) — if a table visibly has
     more columns (e.g. a "Mobile" column) than the tokens tool returned distinct values for, fall
     back to a screenshot of that specific table and read it visually rather than assuming the
     missing column is identical to the one you got.
   - If no Figma tool is connected: tell the user plainly that you need a Figma MCP server
     connected — either the official Figma Dev Mode MCP server (OAuth login, enabled from the
     Figma desktop app or `https://mcp.figma.com`) or a community token-based server (e.g.
     Framelink's `figma-developer-mcp`, which authenticates with a Figma personal access token
     instead of OAuth and works well in non-interactive sessions) — or the raw values pasted in
     manually. Ask which they'd prefer. Don't attempt to scrape the Figma web app via a generic
     web-fetch tool — it won't render without a logged-in session.
4. Once you can read the file, locate the top-level section named **"Variables"** on the page
   behind the link (search by name via whichever metadata/outline tool your Figma access
   provides). If this run will hand off to `import-figma-ui`'s other phases afterward, also note
   the node IDs for the **"Web assets"** block and the Typekit typeface rows inside "Variables"
   now — the sibling skills those phases hand off to need the same Figma access and will ask you
   to re-locate them otherwise, so passing the IDs along saves duplicate work.
   - **Fetch large containers shallow, then drill down — don't dump a whole page in one call.** If
     the node behind the given link is a big container rather than "Variables" itself (e.g. the
     link points at a page-level frame like "UI Kit" that wraps the entire page's content), a
     full-depth fetch of it can be megabytes of data and fail outright (e.g. Framelink's
     `get_figma_data` erroring that the result exceeds the maximum token count). Fetch it with a
     shallow depth first (e.g. `depth: 1`) to see its immediate children's names, then re-fetch by
     the specific child node ID you actually need — repeating one level at a time if that child is
     itself another large container — instead of guessing a depth deep enough to reach "Variables"
     in a single call.

## Phase 1 — Variables → `_variables.scss`

Everything in this phase writes into `libs/<app>/shared/ui/styles/_variables.scss`. Read the
current file first — the shape below is what the generator produces by default, but treat it as a
starting example, not a spec to enforce if the file has already diverged:

```scss
$mobile: 767px;
$tablet: 1023px;
$small-desktop: 1199px;

:root {
  --brand-primary: #bf4b4b;
  --background-primary: #f7f6f2;
  --text-primary: #241b17;

  --font-size-h1: 48px;
  --font-size-default: 16px;

  --max-content-width: 1200px;
  --screen-padding: 16px;

  @media (max-width: $mobile) {
    --font-size-h1: 28px;
    --font-size-default: 14px;
  }
}
```

Note the naming convention actually in use: every design token is a **CSS custom property**
(`--kebab-case-name`) declared inside `:root`, not a Sass `$variable` — the only real `$variables`
in this file are the three breakpoints at the top. Follow whatever this file already does; if it
has genuinely diverged from the shape above, match its current convention instead.

**If a value looks suspicious, render it and look before writing it down.** Structured Figma data
can contain copy-paste leftovers same as any design file — e.g. a row's mobile value happening to
exactly match an unrelated row (a breakpoint value reappearing as a spacing value), or a column
that's visibly blank/dash for every other row but populated for one. Don't silently trust the
dump in that case; render the specific table/row as an image with your Figma tool and read it
visually to confirm before writing the value, the same way Phase 0 already tells you to do when a
tokens tool's color-mode coverage looks incomplete.

1. **Colors.** In the "Variables" block, find the color table. It typically has a "Palette" column
   (raw primitive colors) and a "Light" column (the semantic value the app actually consumes,
   since this app has no dark theme) — read the table as it actually exists on the page, column
   names and layout can vary per project. For each semantic row, take the resolved color from the
   theme column actually used by the app (usually "Light"), and derive the token name from the
   row's grouping path by lowercasing and joining with hyphens, e.g. `Brand / Primary` →
   `--brand-primary`, `Background / Secondary` → `--background-secondary`. Skip adding a
   standalone token for a raw palette primitive unless the user specifically asks for the
   primitives too — the app only consumes the semantic layer.
   - **Write every color as hex, not `rgb()`/`rgba()`, so the file stays visually consistent.** A
     solid color becomes 6-digit hex (`rgb(191, 75, 75)` → `#bf4b4b`); a color with alpha becomes
     8-digit hex — append the alpha as a two-digit hex byte (`round(alpha × 255)` in hex, e.g. 40%
     → `0.4 × 255 ≈ 102 = 0x66`) to the 6-digit color, e.g. `rgba(191, 75, 75, 0.4)` →
     `#bf4b4b66`. Do this even though `npm run lint:css`'s `--fix` will normalize plain
     `rgb()`/`rgba()` calls to the modern space-separated syntax rather than hex — Stylelint does
     not rewrite hex either direction, so writing hex yourself is the only way to get a
     consistently hex file. If the design tool gives you a color as a named CSS keyword (e.g.
     `transparent`) instead of a numeric value, leave it as-is rather than forcing a hex
     equivalent.
2. **Font sizes.** Find the typekit/typography table's font-size rows (desktop and mobile columns,
   possibly named "Typekit", "Desktop", "Mobile", or similar headers — read what's actually there).
   For each size (headings and any named text sizes like large/default/small): the desktop value
   becomes a top-level token inside `:root` (e.g. `--font-size-h1: 48px;`); the mobile value for
   the _same_ token name goes inside the `@media (max-width: $mobile) { ... }` block nested inside
   `:root` — create that block if it's missing, matching the existing indentation style. **Write
   the raw pixel value from the table as `px`, not `rem`** — don't divide by the root font size.
   Don't duplicate a token at both levels with the same value; only add the mobile override if the
   mobile value actually differs from desktop. A token already in the file that has no
   corresponding row in this table (e.g. a "Large" size the table doesn't list) is out of scope —
   leave it exactly as-is rather than guessing a Figma-derived value for it (including its unit —
   don't convert an existing `rem` token to `px` just because new tokens use `px`).
3. **Everything else (responsive/spacing values).** Any other rows in the Variables block (e.g.
   max content width, screen padding, grid gaps) become flat top-level tokens the same way,
   following the same naming transform. If a value differs between desktop and mobile, it follows
   the same media-query placement rule as font sizes above.
4. **Merge, don't clobber.** If `_variables.scss` already has tokens not present in the Figma page,
   leave them — this phase adds/updates tokens sourced from Figma, it doesn't prune the file.
5. After writing, run `npm run lint:css` from the repo root (or the equivalent Stylelint script if
   this repo doesn't have exactly that name — check `package.json`) and fix anything it flags.

## Finishing up

Post a short summary: the token/color/font-size counts written to `_variables.scss`. If you're
running as part of `import-figma-ui`, say this is its "Variables" phase and hand back the Figma
link/access, `<app>`, and any "Web assets"/Typekit node IDs you noted in Phase 0 so the remaining
phases don't have to re-locate them. If you ran standalone, ask the user to visually verify the
app — colors and type sizes at both desktop and mobile widths — since this skill can't render the
app to check that itself.
